import {isTrustedRequest} from '@/lib/request-security';
import {db,identity,clean} from '@/lib/store';
export const dynamic='force-dynamic';
const json=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function presence(d:any){const row=await d.prepare("SELECT value FROM settings WHERE key='support_presence'").first();let v:any={};try{v=JSON.parse(row?.value||'{}')}catch{}return {online:v.online===true&&v.seen>Date.now()-90000};}
export async function GET(r:Request){try{const d=db(),u=await identity(r),p=await presence(d),q=new URL(r.url).searchParams,id=q.get('id');if(q.get('view')==='presence')return json(p);if(!u)return json({error:'Entre para conversar com o HD Studio.'},401);if(id){const t=await d.prepare('SELECT * FROM tickets WHERE id=?').bind(id).first();if(!t||(!u.canSupport&&t.customer_id!==u.id))return json({error:'Conversa não encontrada.'},404);const before=Number(q.get('before')||0);const rows=await d.prepare('SELECT id,sender,body,created FROM ticket_messages WHERE ticket_id=? AND (?=0 OR created<?) ORDER BY created DESC,id DESC LIMIT 100').bind(id,before,before).all();return json({...p,ticket:t,messages:rows.results.reverse(),hasMore:rows.results.length===100,typing:t.status==='open'&&(u.canSupport?t.customer_typing:t.owner_typing)>Date.now()-5000});}const list=u.canSupport?await d.prepare('SELECT * FROM tickets ORDER BY updated DESC').all():await d.prepare('SELECT * FROM tickets WHERE customer_id=? ORDER BY updated DESC LIMIT 100').bind(u.id).all();return json({...p,tickets:list.results});}catch(e){console.error(e);return json({error:'Chat indisponível. Tente novamente.'},503);}}
export async function POST(r:Request){try{if(!isTrustedRequest(r))return json({error:'Origem inválida.'},403);const u=await identity(r);if(!u)return json({error:'Entre para conversar.'},401);const raw=await r.text();if(raw.length>6000)return json({error:'Mensagem muito longa.'},413);const b=JSON.parse(raw),d=db(),now=Date.now();if(b.action==='presence'){if(!u.canSupport)return json({error:'Acesso exclusivo do dono e administradores e administradores.'},403);await d.prepare("INSERT INTO settings(key,value) VALUES('support_presence',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify({online:b.online===true,seen:now})).run();return json({ok:true});}
if(b.action==='create'){if(u.canSupport)return json({error:'Responda uma conversa na seção Tickets.'},400);const existing=await d.prepare("SELECT id FROM tickets WHERE customer_id=? AND status='open' ORDER BY updated DESC LIMIT 1").bind(u.id).first();if(existing)return json(existing);const id=crypto.randomUUID();await d.prepare("INSERT INTO tickets(id,customer_id,customer_name,status,created,updated) SELECT ?,?,?,'open',?,? WHERE NOT EXISTS(SELECT 1 FROM tickets WHERE customer_id=? AND status='open') ON CONFLICT DO NOTHING").bind(id,u.id,u.name.slice(0,120),now,now,u.id).run();const current=await d.prepare("SELECT id FROM tickets WHERE customer_id=? AND status='open' ORDER BY updated DESC LIMIT 1").bind(u.id).first();return json(current);}
const id=clean(b.ticketId,80),t=await d.prepare('SELECT * FROM tickets WHERE id=?').bind(id).first();if(!t||(!u.canSupport&&t.customer_id!==u.id))return json({error:'Conversa não encontrada.'},404);
if(b.action==='status'){if(!u.canSupport)return json({error:'Acesso exclusivo do dono e administradores e administradores.'},403);if(!['open','closed'].includes(b.status))return json({error:'Status inválido.'},400);await d.prepare('UPDATE tickets SET status=?,updated=?,owner_typing=0,customer_typing=0 WHERE id=?').bind(b.status,now,id).run();return json({ok:true});}
if(b.action==='typing'){if(t.status!=='open')return json({ok:true});await d.prepare(u.canSupport?'UPDATE tickets SET owner_typing=? WHERE id=?':'UPDATE tickets SET customer_typing=? WHERE id=?').bind(b.active===true?now:0,id).run();return json({ok:true});}
if(b.action==='message'){if(t.status!=='open')return json({error:'Esta conversa está fechada.'},409);const body=clean(b.body,2000),mid=clean(b.id,80);if(!/^[0-9a-f-]{36}$/.test(mid))return json({error:'Mensagem inválida.'},400);const exists=await d.prepare('SELECT ticket_id,sender FROM ticket_messages WHERE id=?').bind(mid).first();if(exists){if(exists.ticket_id!==id||exists.sender!==(u.canSupport?'owner':'customer'))return json({error:'Mensagem inválida.'},409);return json({ok:true});}const result=await d.batch([d.prepare("INSERT INTO ticket_messages(id,ticket_id,sender,body,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM tickets WHERE id=? AND status='open')").bind(mid,id,u.canSupport?'owner':'customer',body,now,id),d.prepare(u.canSupport?'UPDATE tickets SET updated=?,owner_typing=0 WHERE id=?': 'UPDATE tickets SET updated=?,customer_typing=0 WHERE id=?').bind(now,id)]);if(!result[0].meta.changes)return json({error:"Esta conversa foi fechada. Sua mensagem não foi enviada."},409);return json({ok:true});}return json({error:'Ação inválida.'},400);}catch(e){console.error(e);return json({error:'Não foi possível salvar. Confira sua conexão e tente novamente.'},400);}}
