import {isTrustedRequest} from '@/lib/request-security';
import { db,identity,clean,cents,delivery,pix,key } from '@/lib/store';
export const dynamic='force-dynamic';
const json=(v:any,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(r:Request){try{const u=await identity(r),q=new URL(r.url).searchParams,view=q.get('view');const d=db();if(view==='me')return json({user:u});if(view==='products'){const rows=await d.prepare('SELECT id,name,description,category,price FROM products WHERE active=1 ORDER BY created DESC').all();return json(rows.results);}if(view==='dashboard'){if(!u?.owner)return json({error:'Acesso exclusivo do dono.'},403);const [p,c,o,clients,settings]=await Promise.all([d.prepare('SELECT * FROM products ORDER BY created DESC').all(),d.prepare('SELECT * FROM coupons ORDER BY code').all(),d.prepare('SELECT o.*,c.name AS customer_name,c.email AS customer_email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.created DESC').all(),d.prepare('SELECT c.*,COUNT(o.id) AS orders_count,COALESCE(SUM(CASE WHEN o.status=\'paid\' THEN o.total ELSE 0 END),0) AS spent FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id ORDER BY c.created DESC').all(),d.prepare('SELECT * FROM settings').all()]);return json({products:p.results,coupons:c.results,orders:o.results,clients:clients.results,settings:settings.results});}if(view==='orders'){if(!u)return json({error:'Entre para continuar.'},401);const rows=await d.prepare("SELECT id,product_name,total,status,created,CASE WHEN status='paid' THEN delivery ELSE '' END AS delivery FROM orders WHERE customer_id=? ORDER BY created DESC").bind(u.id).all();return json(rows.results);}if(view==='pix'){const s=await d.prepare("SELECT value FROM settings WHERE key='city'").first();return json({key,name:'Tiago Pereira da Silva',payload:s?.value?pix(s.value):null});}return json({error:'Não encontrado'},404);}catch(e){console.error(e);return json({error:'Não foi possível carregar. Tente novamente.'},503);}}
export async function POST(r:Request){try{if(!isTrustedRequest(r))return json({error:'Origem inválida'},403);const u=await identity(r);if(!u)return json({error:'Entre para continuar.'},401);if(Number(r.headers.get('content-length')||0)>16000)return json({error:'Dados muito grandes'},413);const body=await r.text();if(body.length>16000)return json({error:'Dados muito grandes'},413);const b=JSON.parse(body),d=db(),now=new Date().toISOString();if(['product','coupon','status','city'].includes(b.action)&&!u.owner)return json({error:'Acesso exclusivo do dono.'},403);
if(b.action==='product'){const id=b.id?clean(b.id,80):crypto.randomUUID();const price=cents(b.price),cost=cents(b.cost||0);if(price<1)throw new Error('Informe um preço maior que zero');await d.prepare('INSERT INTO products(id,name,description,category,price,cost,active,delivery,created) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,price=excluded.price,cost=excluded.cost,active=excluded.active,delivery=excluded.delivery').bind(id,clean(b.name,100),clean(b.description,3000),clean(b.category,60),price,cost,b.active===false?0:1,delivery(b.delivery),now).run();return json({ok:true});}
if(b.action==='coupon'){const code=clean(b.code,40).toUpperCase();if(!/^[A-Z0-9_-]+$/.test(code))throw new Error('Use letras, números, hífen ou sublinhado no cupom');const percent=Number(b.percent);if(!Number.isInteger(percent)||percent<1||percent>99)throw new Error('Desconto deve ser de 1% a 99%');await d.prepare('INSERT INTO coupons(code,percent,active) VALUES(?,?,?) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,active=excluded.active').bind(code,percent,b.active===false?0:1).run();return json({ok:true});}
if(b.action==='city'){const city=clean(b.city,80);pix(city);await d.prepare("INSERT INTO settings(key,value) VALUES('city',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(city).run();return json({ok:true});}
if(b.action==='status'){if(!['paid','cancelled','pending'].includes(b.status))throw new Error('Status inválido');const result=await d.prepare('UPDATE orders SET status=?,paid=? WHERE id=?').bind(b.status,b.status==='paid'?now:null,clean(b.id,80)).run();if(!result.meta.changes)throw new Error('Pedido não encontrado');return json({ok:true});}
if(b.action==='quote'||b.action==='order'){const p=await d.prepare('SELECT * FROM products WHERE id=? AND active=1').bind(clean(b.productId,80)).first();if(!p)throw new Error('Produto indisponível');let percent=0,code=typeof b.coupon==='string'?b.coupon.trim().toUpperCase():'';if(code){const c=await d.prepare('SELECT * FROM coupons WHERE code=? AND active=1').bind(clean(code,40)).first();if(!c)throw new Error('Cupom inválido ou inativo');percent=c.percent;}const total=p.price-Math.floor(p.price*percent/100);if(b.action==='quote')return json({subtotal:p.price,total,percent});const id=clean(b.id,80);if(!/^[0-9a-f-]{36}$/.test(id))throw new Error('Pedido inválido');const existing=await d.prepare('SELECT id,customer_id,total,subtotal FROM orders WHERE id=?').bind(id).first();if(existing){if(existing.customer_id!==u.id)return json({error:'Pedido inválido'},403);return json(existing);}await d.batch([d.prepare('INSERT INTO customers(id,name,email,created) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email').bind(u.id,u.name,u.email,now),d.prepare('INSERT INTO orders(id,customer_id,product_id,product_name,subtotal,total,cost,coupon,status,delivery,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,u.id,p.id,p.name,p.price,total,p.cost,code,'pending',p.delivery,now)]);return json({id,total,subtotal:p.price});}
return json({error:'Ação inválida'},400);}catch(e){console.error(e);return json({error:e instanceof Error&& !/SQL|D1|database/i.test(e.message)?e.message:'Não foi possível salvar. Tente novamente.'},400);}}
