'use client';
import {useEffect,useState} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const roles:Record<string,string>={owner:'Dono',customer:'Cliente',admin:'Administrador',moderator:'Moderador',seller:'Vendedor',partner:'Parceiro',support:'Atendente'};
export default function Administration(){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setData(null);const timer=setTimeout(()=>{fetch('/api/admin?q='+encodeURIComponent(query)+'&page='+page,{signal:controller.signal,cache:'no-store'}).then(async r=>{const b:any=await r.json();if(!r.ok)throw new Error(b.error);setData(b);setError('')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)})},250);return()=>{clearTimeout(timer);controller.abort()}},[query,page]);
 async function change(id:string,role:string){setBusy(id);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,role})}),b:any=await r.json();if(!r.ok)throw new Error(b.error);setData((d:any)=>({...d,users:d.users.map((u:any)=>u.id===id?{...u,role}:u)}))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <div className="panel"><h2>Contas e permissões</h2><p>Somente você, dono, pode alterar os cargos. Dono e administradores podem ler e responder aos chats. Moderador, vendedor, parceiro e atendente não recebem esse acesso.</p>{data&&!data.emailReady&&<p className="notice">Novos cadastros estão pausados até ativar o envio de códigos por e-mail.</p>}<label htmlFor="admin-search">Buscar por nome ou e-mail</label><input className="admin-search" id="admin-search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Digite um nome ou e-mail"/>{error&&<p role="alert" className="chat-error">{error}</p>}{!data?<p role="status">Carregando contas…</p>:<><div className="admin-table"><Table><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>E-mail</TableHead><TableHead>Cadastro</TableHead><TableHead>Cargo</TableHead></TableRow></TableHeader><TableBody>{data.users.map((u:any)=><TableRow key={u.id}><TableCell>{u.name}</TableCell><TableCell>{u.email}</TableCell><TableCell>{new Date(u.created).toLocaleDateString('pt-BR')}</TableCell><TableCell>{u.role==='owner'?<span className="badge">Dono · protegido</span>:<Select value={u.role} disabled={busy===u.id} onValueChange={v=>change(u.id,v)}><SelectTrigger aria-label={'Cargo de '+u.email}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(roles).filter(([k])=>k!=='owner').map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select>}</TableCell></TableRow>)}{!data.users.length&&<TableRow><TableCell colSpan={4}>Nenhuma conta encontrada.</TableCell></TableRow>}</TableBody></Table></div><div className="otp-actions"><button className="button secondary" disabled={!page} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1}</span><button className="button secondary" disabled={!data.hasMore} onClick={()=>setPage(page+1)}>Próxima</button></div></>}</div>
}
